#include<stdio.h>
#include<math.h>

/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

//First, calculate the next triangle number.
//Second, find divisors and tally them

long main()	{
	long long i=1;
	long long triangle=1;
	int limit=500;
	int divisors=1;
	while (divisors<limit)	{
		i++;
		triangle+=i;
		divisors=calcDivisors(triangle);
	}
	printf("%ld\n",triangle);
	return triangle;
}

int calcDivisors(triangle)	{
	int tally=0;
	int i;
	double sqrtTri=sqrt((double)triangle);
	for (i=1;(double)i<=sqrtTri;i++)	{
		if (triangle%i==0)	{
			tally+=2;
		}
	}
	if (sqrtTri==0)	{
		tally--;
	}
	return tally;
}