#include <stdio.h>

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

int main ()	{
	int limit=4000000;
	int sum=0;
	int tmp=0;
	int i=1;
	while (tmp<=limit)	{
		tmp=fibonacci(i);
		if (tmp%2==0 && tmp<=limit)	{
			sum+=tmp;
		}
		i++;
	}
	
	printf("%d\n",sum);
	return sum;
}

int fibonacci(int n)	{
	int tmp=0;
	if (n==1)	{
		tmp=1;
	}	else if (n==2)	{
		tmp=1;
	}	else	{
		tmp=fibonacci(n-1)+fibonacci(n-2);
	}
	return tmp;
}