#include <stdio.h>

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

int main ()	{
	unsigned int limit=4000000;
	unsigned int fib[3];
	fib[0]=1;
	fib[1]=2;
	fib[2]=3;
	unsigned int sum=fib[1];
	while (fib[2]<=limit)	{
		fib[2]=fib[1]+fib[0];
		fib[0]=fib[1];
		fib[1]=fib[2];
		if (fib[2]%2==0 && fib[2]<=limit)	{
			sum+=fib[2];
		}
	}
	
	printf("%d\n",sum);
	return sum;
}